# Generated by Django 4.1 on 2023-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='side',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
